language: 
  - node_js
node_js:
  - '8'
  - '9'
  - stable'
sudo: required
dist: trusty
addons:
  chrome: stable
cache: bundler
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script: 
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  - ng test