language: 
  - node_js
node_js:
  - '8'
  - '9'
  - 'stable'
sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222
script: 
  - ng test