language: 
  - node_js
node_js:
  - '8'
  - '9'
  - 'stable'
sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script: 
  - ng test