language: 
  - node_js
node_js:
  - '8'
  - '9'
  - 'stable'
sudo: required
dist: trusty
addons:
  chrome: stable
cache: bundler
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script: 
  - ng test